import Navbar from './components/Navbar'

import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import { PageProvider } from '../app/context/pageContext';
import Footer from './components/Footer'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <PageProvider>
          <div><Navbar /></div>
          <div>{children}</div>
          <div><Footer /></div>
        </PageProvider>
      </body>
    </html>
  )
}
